apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapfinance-app
  labels:
    app: snapfinance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snapfinance
  template:
    metadata:
      labels:
        app: snapfinance
    spec:
      containers:
      - name: snapfinance
        image: dcerdassan/devopssnapfinance:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

      imagePullSecrets:
        - name: dockerhub-creds
