apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapfinance-app
  labels:
    app: snapfinance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snapfinance
  template:
    metadata:
      labels:
        app: snapfinance
    spec:
      containers:
      - name: snapfinance
        image: dcerdassan/devopssnapfinance:v1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

        # 👇 Startup Probe — espera que la app levante correctamente antes de los otros probes
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 15   # intentará durante 2.5 minutos (15 x 10s)
          periodSeconds: 10

        # 👇 Liveness Probe — reinicia el contenedor si se cuelga
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

        # 👇 Readiness Probe — controla si el pod puede recibir tráfico
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

