apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapfinance-app
  labels:
    app: snapfinance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snapfinance
  template:
    metadata:
      labels:
        app: snapfinance
    spec:
      containers:
      - name: snapfinance
        image: dcerdassan/devopssnapfinance:v1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
