apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapfinance-app
  labels:
    app: snapfinance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snapfinance
  template:
    metadata:
      labels:
        app: snapfinance
    spec:
      containers:
      - name: snapfinance
        image: dcerdassan/devopssnapfinance:v1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

        # 👇 Startup Probe — ensures the app has enough time to start before other probes are applied
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30   # will try for ~5 minutes (30 x 10s)
          periodSeconds: 10

        # 👇 Liveness Probe — restarts the container if it stops responding
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        # 👇 Readiness Probe — controls when the pod is ready to receive traffic
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
