pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dcerdassan/devopssnapfinance"
        BUILD_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Cleaning workspace and cloning repo from GitHub (main branch)..."
                deleteDir()
                // Checkout main branch to get the application code
                git branch: 'main',
                    url: 'https://github.com/Alephdjcs/devops-challenge.git',
                    credentialsId: 'github-token'
            }
        }

        stage('Pre-Build Script') {
            steps {
                echo "Running pre-build script..."
                sh 'bash ${WORKSPACE}/jenkins/scripts/pre_build.sh'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image..."
                    docker.build("${DOCKER_IMAGE}:${BUILD_TAG}", "./application")
                    echo "Docker image built: ${DOCKER_IMAGE}:${BUILD_TAG}"
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        echo "Logging in to Docker Hub..."
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'

                        echo "Pushing Docker image to Docker Hub..."
                        sh "docker push ${DOCKER_IMAGE}:${BUILD_TAG}"
                        echo "Image successfully pushed: ${DOCKER_IMAGE}:${BUILD_TAG}"
                    }
                }
            }
        }

        stage('Cleanup Old Docker Images') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        echo "Running cleanup script for old Docker images..."
                        sh 'bash ${WORKSPACE}/jenkins/scripts/cleanup_old_images.sh'
                    }
                }
            }
        }

        stage('Post-Build Script') {
            steps {
                echo "Running post-build script..."
                sh 'bash ${WORKSPACE}/jenkins/scripts/post_build.sh'
            }
        }
