pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dcerdassan/devopssnapfinance"
        BUILD_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "🔄 Clonando el repo desde GitHub..."
                git branch: 'main',
                    url: 'https://github.com/Alephdjcs/devops-challenge.git',
                    credentialsId: 'github-token'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "🔨 Construyendo la imagen Docker..."
                    docker.build("${DOCKER_IMAGE}:${BUILD_TAG}", "./application")
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    echo "🚀 Logueando y subiendo la imagen a Docker Hub..."
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${DOCKER_IMAGE}:${BUILD_TAG}"
                }
            }
        }
    }

    post {
        success {
            echo "✅ Imagen construida y subida correctamente a Docker Hub"
        }
        failure {
            echo "❌ Falló el pipeline"
        }
    }
}
